#:schema node_modules/wrangler/config-schema.json
name = "acecourtbot-web"
main = "src/index.js"
compatibility_date = "2024-07-25"
compatibility_flags = ["nodejs_compat"]

rules = [
  { type = "Data", globs = ["**/*.woff"], fallthrough = true },
  { type = "Data", globs = ["**/*.png"], fallthrough = true },
  { type = "Data", globs = ["**/*.ico"], fallthrough = true },
  { type = "Text", globs = ["**/*.webmanifest"], fallthrough = true },
]